"""
ArchWeaver: Dependency Resolver
Uses topological sort to determine correct generation order
"""
from collections import deque

class Resolver:
    def resolve(self, dag):
        """
        Resolve dependencies using Kahn's topological sort algorithm
        Returns: Sorted list of components in generation order
        """
        components = dag.get("components", [])
        dependencies = dag.get("dependencies", {})
        
        graph = {comp: [] for comp in components}
        indegree = {comp: 0 for comp in components}
        
        for comp, deps in dependencies.items():
            for dep in deps:
                if dep in graph:
                    graph[dep].append(comp)
                    indegree[comp] += 1
        
        queue = deque([comp for comp in components if indegree[comp] == 0])
        sorted_order = []
        
        while queue:
            comp = queue.popleft()
            sorted_order.append(comp)
            for neighbor in graph.get(comp, []):
                indegree[neighbor] -= 1
                if indegree[neighbor] == 0:
                    queue.append(neighbor)
        
        if len(sorted_order) != len(components):
            raise Exception("Circular dependency detected in UVM components!")
        
        return sorted_order
    
    def get_generation_order(self, dag):
        sorted_order = self.resolve(dag)
        filename_map = {
            "interface": "interface.sv",
            "sequence_item": "seq_item.sv",
            "sequence": "sequence.sv",
            "driver": "driver.sv",
            "monitor": "monitor.sv",
            "agent": "agent.sv",
            "scoreboard": "scoreboard.sv",
            "coverage": "coverage.sv",
            "env": "env.sv",
            "test_base": "test_base.sv",
            "test_directed": "test_directed.sv",
            "top": "top.sv"
        }
        result = []
        for i, comp in enumerate(sorted_order):
            if comp in filename_map:
                result.append({
                    "component": comp,
                    "filename": filename_map[comp],
                    "order": i + 1
                })
        return result
    
    def export_dot(self, dag, filename="dag.dot"):
        """Export DAG to DOT format for Graphviz visualization"""
        dependencies = dag.get("dependencies", {})
        components = dag.get("components", [])
        
        lines = [
            "// VeriGenX UVM Component Dependency Graph",
            "// Generated by ArchWeaver",
            "digraph G {",
            '    rankdir=TB;',
            '    node [shape=box, style=filled, fillcolor=lightblue];',
            '    edge [color=darkblue];',
            ''
        ]
        
        for comp in components:
            lines.append(f'    "{comp}" [label="{comp}"];')
        
        lines.append('')
        
        for comp, deps in dependencies.items():
            for dep in deps:
                if dep in components:
                    lines.append(f'    "{dep}" -> "{comp}";')
        
        lines.append("}")
        
        with open(filename, 'w') as f:
            f.write("\n".join(lines))
        
        print(f"DOT file exported to: {filename}")
        print("To visualize: Install Graphviz and run:")
        print(f"  dot -Tpng {filename} -o dag.png")
        return filename
