import os
import pytest
import pandas as pd
from unittest.mock import MagicMock, patch

from VeriGenX.agents.wavewhisperer.vcd_reader import VCDReader
from VeriGenX.agents.wavewhisperer.anomaly_detector import AnomalyDetector
from VeriGenX.agents.wavewhisperer.explainer import WaveExplainer
from VeriGenX.agents.wavewhisperer import WaveWhisperer

@pytest.fixture
def synthetic_vcd(tmp_path):
    vcd_content = """$version Generated by Test $end
$timescale 1ns $end
$scope module TOP $end
$var wire 1 " clk $end
$var wire 1 # rst_n $end
$var wire 1 $ data $end
$var wire 8 % state $end
$upscope $end
$enddefinitions $end
#0
0"
0#
1$
b00000000 %
#5
1"
1#
1$
b00000001 %
#10
0"
#12
x$
#14
1$
#15
1"
b00000011 %
#20
0"
"""
    vcd_file = tmp_path / "synthetic.vcd"
    with open(vcd_file, "w", encoding="utf-8") as f:
        f.write(vcd_content)
    return str(vcd_file)

@pytest.fixture
def mock_test_plan():
    return {
        "design_name": "uart",
        "signals": [
            {"name": "clk", "width": 1, "direction": "input"},
            {"name": "rst_n", "width": 1, "direction": "input"},
            {"name": "data", "width": 1, "direction": "input"},
            {"name": "state", "width": 8, "direction": "output"}
        ],
        "fsm_states": [
            "IDLE",
            "START",
            "DATA",
            "STOP"
        ],
        "timing_constraints": {
            "setup_time_ns": 2,
            "hold_time_ns": 2
        },
        "protocol_handshake_rules": [
            "Start bit initiates transaction"
        ]
    }

def test_vcd_reader(synthetic_vcd):
    reader = VCDReader(synthetic_vcd)
    df = reader.parse()
    
    assert not df.empty
    assert "clk" in df.columns
    assert "rst_n" in df.columns
    assert "data" in df.columns
    assert "state" in df.columns
    
    # Check forward filling behavior
    assert df.loc[5, "data"] == 1
    assert df.loc[12, "data"] == "X"

def test_anomaly_detector(synthetic_vcd, mock_test_plan):
    reader = VCDReader(synthetic_vcd)
    df = reader.parse()
    
    detector = AnomalyDetector("uart", mock_test_plan)
    anomalies = detector.detect_anomalies(df)
    
    assert len(anomalies) > 0
    
    # Check for specific anomaly detections
    types = [a["type"] for a in anomalies]
    assert "XZ_PROPAGATION" in types
    assert "RESET_VIOLATION" in types
    assert "GLITCH_DETECTION" in types
    assert "FSM_SEQUENCE_VIOLATION" in types

@patch("VeriGenX.agents.wavewhisperer.explainer.get_ollama_client")
def test_wave_explainer(mock_get_client, mock_test_plan):
    mock_client = MagicMock()
    mock_client.is_available.return_value = True
    mock_client.generate.return_value = "1. What happened: Setup violation occurred.\n2. Why: The signal changed within setup window.\n3. Suggested fix: Restructure flip-flop registers."
    mock_get_client.return_value = mock_client
    
    anomalies = [
        {
            "type": "SETUP_VIOLATION",
            "timestamp": 14,
            "signal": "data",
            "actual": "Changed at 14",
            "expected": "Stable 2 units before edge",
            "severity": "WARNING"
        }
    ]
    
    explainer = WaveExplainer()
    explained = explainer.explain_anomalies("uart", anomalies, mock_test_plan)
    
    assert len(explained) == 1
    assert explained[0]["what_happened"] == "Setup violation occurred."
    assert explained[0]["why"] == "The signal changed within setup window."
    assert explained[0]["suggested_fix"] == "Restructure flip-flop registers."
